# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano@1.0.0//zmk # nice!nano v1
    shield: little_luggable
    artifact-name: little-luggable-nice-nano-v1
  - board: nice_nano@2.0.0//zmk # nice!nano v2
    shield: little_luggable
    artifact-name: little-luggable-nice-nano-v2
