#!/usr/bin/env bash

# Copyright (c) 2018-2026 Jason Morley
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Generate a ZMK `&about` macro that types a fixed identity string.
#
# Usage: generate-about-macro.sh <output-path> <text>
#
# The macro is used to report the firmware identity (device name, version, and
# build number) by typing it out when the corresponding key combination is
# pressed. Keycodes assume a US keyboard layout on the host.

set -e
set -o pipefail
set -u

if [ "$#" -ne 2 ] ; then
    echo "Usage: $(basename "$0") <output-path> <text>" >&2
    exit 1
fi

OUTPUT_PATH="$1"
TEXT="$2"

# Map a single character to the ZMK keycode that produces it (US layout).
emit_keycode() {
    local character="$1"
    case "$character" in
        [a-z]) printf '&kp %s' "$(printf '%s' "$character" | tr '[:lower:]' '[:upper:]')" ;;
        [A-Z]) printf '&kp LS(%s)' "$character" ;;
        [0-9]) printf '&kp N%s' "$character" ;;
        ' ')   printf '&kp SPACE' ;;
        '.')   printf '&kp DOT' ;;
        '-')   printf '&kp MINUS' ;;
        *)
            echo "error: unsupported character '$character' in about text" >&2
            exit 1
            ;;
    esac
}

# Build the list of key press bindings, one per line.
BINDINGS=$'\n'
for (( i = 0; i < ${#TEXT}; i++ )) ; do
    BINDINGS+="                    $(emit_keycode "${TEXT:$i:1}")"$'\n'
done

cat > "$OUTPUT_PATH" <<EOF
/*
 * Auto-generated by scripts/generate-about-macro.sh - do not edit by hand.
 *
 * Defines the &about macro, which types the firmware identity string:
 *
 *     $TEXT
 *
 * The committed copy uses placeholder values; the build regenerates it with
 * the real version and build number.
 */

/ {
    macros {
        about: about {
            compatible = "zmk,behavior-macro";
            #binding-cells = <0>;
            label = "ABOUT";
            wait-ms = <10>;
            tap-ms = <30>;
            bindings
                = <&macro_tap${BINDINGS}                >;
        };
    };
};
EOF
