theme: theme
title: Little Luggable
author: Jason Morley
email: support@jbmorley.co.uk
description: Raspberry Pi Cyberdeck
image: images/hero.jpg
baseurl: ""
url: "https://little-luggable.jbmorley.co.uk"
repository: https://github.com/jbmorley/little-luggable
copyright: 2022-2026 <a href="https://jbmorley.co.uk/about">Jason Morley</a>

primary_action:
  title: Download
  href: /downloads

navigation:
  - title: Little Luggable
    href: /
  - title: Gallery
    href: /gallery
  - title: Documentation
    href: /docs
  - title: Downloads
    href: /downloads
  - title: Source
    href: https://github.com/jbmorley/little-luggable
  - title: More
    href: https://jbmorley.co.uk/projects/
  - title: Donate ❤️
    href: https://jbmorley.co.uk/donate/

glossary:
    little-keyboard-firmware: Little Keyboard &ndash; Firmware
    little-keyboard-settings-reset: Little Keyboard &ndash; Settings Reset Firmware
    nice-nano: nice!nano
    nice-nano-v1: nice!nano (v1)
    nice-nano-v2: nice!nano (v2)
    zmk: ZMK


footer:
  - title: License
    href: /license
  - title: AI
    href: /ai

destination: ../_site

toc:
  ordered_list: true

gfm_admonitions:
  inject_css: false

defaults:
  - values:
      layout: "page"
  - scope:
      path: "docs"
    values:
      layout: "documentation"
      toc: true
      shows_title: true
